import sys;import build540 as b, hashlib
orig=open('SuperHexagon.exe','rb').read()
pat=b.build(orig,9); n=len(orig); sec=pat[n:]
runs=[];i=0
while i<n:
    if orig[i]!=pat[i]:
        j=i
        while j<n and (orig[j]!=pat[j] or (j+1<n and orig[j+1]!=pat[j+1])): j+=1
        runs.append((i,pat[i:j])); i=j
    else: i+=1
D=b.D
def carr(name,data): return 'static const unsigned char %s[%d]={%s};\n'%(name,len(data),','.join(str(x) for x in data))
out='/* generated by genpatch.py -- do not edit */\n'
out+='#define ORIG_SIZE %d\n#define SEC_SIZE %d\n'%(n,len(sec))
out+='static const char ORIG_SHA[]="%s";\n'%hashlib.sha256(orig).hexdigest()
out+='#define OFF_N %d\n#define OFF_IDX %d\n#define OFF_TABLE %d\n#define OFF_VERSION %d\n#define PATCH_VERSION %d\n'%(D['N'],D['idx'],D['table'],D['version'],b.VERSION)
out+=carr('SEC_BLOB',sec)
out+=carr('RUN_DATA',b''.join(r[1] for r in runs))
out+='static const unsigned int RUN_OFF[%d]={%s};\n'%(len(runs),','.join(str(r[0]) for r in runs))
out+='static const unsigned int RUN_LEN[%d]={%s};\n#define NRUNS %d\n'%(len(runs),','.join(str(len(r[1])) for r in runs),len(runs))
open('patchdata.h','w').write(out)
t=bytearray(orig)
for o,d in runs: t[o:o+len(d)]=d
assert bytes(t)+sec==pat
print('runs',len(runs),'sec',len(sec),'version',b.VERSION)
